"""
Table 3 — Leverage and investment (manuscript tab:inv_main).

Replicates panel regressions from the original Stata A9_inv_results.do (removed from tree; git show d54b0c3:code/legacy/mete/A9_inv_results.do) with column
definitions from manuscript/tables/body/3_investment_reg.tex.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import pandas as pd

from config import PANEL_PATH, COEF_TOLERANCE, MANUSCRIPT_BODY_TABLES, MANUSCRIPT_BODY_TABLES
from pipeline.io import read_dta
from lib.regressions import fit_classic, fit_overhang
from tables.render.investment_reg import render_table3_latex


@dataclass
class ColumnSpec:
    label: str
    exposure: str = "d"
    sample: str = "full"


# Tolerance for the adopted cols 4-5 sample reconstructions vs the published
# table (exact definitions lost with the RFS-era A9 do-file; D-016).
RECON_TOLERANCE = 0.02


def load_panel() -> pd.DataFrame:
    return read_dta(PANEL_PATH)


def _exclude_repurchasers(df: pd.DataFrame) -> pd.Series:
    """Column 4 sample: drop firms whose gold exposure d went from positive to
    zero during the litigation window (1931-1935), i.e. firms that retired
    their gold-clause debt. This is Mete's A16_balanced.do ``repay`` flag
    (Stata: gen repay2 = 1 if d == 0 & L.d > 0 & year >= 1931 & year <= 1935),
    adopted as the closest reconstruction of the published column 4 (published
    d = -0.097, N = 5,572; this sample gives d = -0.094, N = 5,918; the
    original RFS-era do-file defining the exact sample is lost)."""
    lag = df[["permno", "year", "d"]].copy()
    lag["year"] += 1
    lag = lag.rename(columns={"d": "_Ld"})
    m = df[["permno", "year", "d"]].merge(lag, on=["permno", "year"], how="left")
    repay2 = (m["d"] == 0) & (m["_Ld"] > 0) & m["year"].between(1931, 1935)
    bad = set(m.loc[repay2.to_numpy(), "permno"])
    return ~df["permno"].isin(bad)


def _positive_ltl_sample(df: pd.DataFrame) -> pd.Series:
    """Column 5 sample: firms with positive (raw balance-sheet) long-term
    liabilities in 1930, the year exposure is measured. Closest
    reconstruction of the published column 5 (published d = -0.057,
    N = 6,048; this sample gives d = -0.052, N = 6,187, with the 1926-1934
    interaction profile matching published within 0.01-0.03)."""
    firms = set(df.loc[(df["year"] == 1930) & (df["ll_bs"] > 0), "permno"])
    return df["permno"].isin(firms)


def run_models(df: pd.DataFrame) -> dict[str, object]:
    specs = [
        ("classic", None),
        ("overhang", "full"),
        ("no_maturity", "no_maturity"),
        ("no_redemption", "no_redemption"),
        ("positive_ltl", "positive_ltl"),
        ("pref_shares", "pref"),
        ("bank_debt", "bank"),
    ]
    models = {}

    models["classic"] = fit_classic(df)

    models["overhang"] = fit_overhang(df, exposure="d")

    models["no_maturity"] = fit_overhang(
        df, exposure="d", sample=df["ind_3134_max"] != 1
    )

    models["no_redemption"] = fit_overhang(
        df, exposure="d", sample=_exclude_repurchasers(df)
    )

    models["positive_ltl"] = fit_overhang(
        df, exposure="d", sample=_positive_ltl_sample(df)
    )

    models["pref_shares"] = fit_overhang(df, exposure="ps")
    models["bank_debt"] = fit_overhang(df, exposure="bd")

    return models


def validate_against_manuscript(models: dict[str, object]) -> list[tuple[str, float, float]]:
    """Return list of (name, expected, actual) for key coefficients."""
    tex = MANUSCRIPT_BODY_TABLES / "3_investment_reg.tex"
    text = tex.read_text(encoding="utf-8")

    # Parse Q row (first numeric line after Q header)
    import re

    def _parse_row(pattern: str) -> list[float | None]:
        match = re.search(pattern, text, re.MULTILINE)
        if not match:
            return []
        row = match.group(1)
        if not row.endswith("&"):
            row = row + "&"
        cells = row.split("&")
        vals: list[float | None] = []
        for cell in cells:
            cell = re.sub(r"\\sym\{[*]+\}", "", cell).strip()
            if not cell:
                vals.append(None)
                continue
            try:
                vals.append(float(cell))
            except ValueError:
                vals.append(None)
        return vals

    q_vals = _parse_row(r"Q\s*&(.*?)\\\\")
    d_vals = _parse_row(r"\\ensuremath\{\\tilde\{d\}\}\s*&(.*?)\\\\")

    order = ["classic", "overhang", "no_maturity", "no_redemption", "positive_ltl", "pref_shares", "bank_debt"]
    # The manuscript table is generated by this builder (adopted 2026-07-21;
    # cols 4-5 use the reconstructed samples in _exclude_repurchasers /
    # _positive_ltl_sample, col 7 SEs the CGM fallback — D-017), so all
    # seven columns validate strictly against it.
    validated_indices = {0, 1, 2, 3, 4, 5, 6}
    recon_indices: set[int] = set()
    checks: list[tuple[str, float, float]] = []
    recon_checks: list[tuple[str, float, float]] = []

    for i, key in enumerate(order):
        m = models[key]
        bucket = checks if i in validated_indices else recon_checks if i in recon_indices else None
        if bucket is None:
            continue
        if i < len(q_vals) and q_vals[i] is not None:
            bucket.append((f"{key}.var_Q", q_vals[i], float(m.coef().loc["var_Q"])))
        exp_name = "ps" if key == "pref_shares" else "bd" if key == "bank_debt" else "d"
        if key != "classic" and i < len(d_vals) and d_vals[i] is not None:
            bucket.append((f"{key}.{exp_name}", d_vals[i], float(m.coef().loc[exp_name])))

    return checks, recon_checks


def write_latex_table(models: dict[str, object], path: Path | None = None) -> Path:
    out = path or (MANUSCRIPT_BODY_TABLES / "3_investment_reg.tex")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_table3_latex(models), encoding="utf-8")
    return out


def main() -> dict[str, object]:
    df = load_panel()
    models = run_models(df)
    checks, recon_checks = validate_against_manuscript(models)

    failures = [
        f"{name}: expected {exp:.4f}, got {act:.4f}"
        for name, exp, act in checks
        if abs(exp - act) > COEF_TOLERANCE
    ]
    recon_failures = [
        f"{name}: expected {exp:.4f}, got {act:.4f}"
        for name, exp, act in recon_checks
        if abs(exp - act) > RECON_TOLERANCE
    ]
    if failures or recon_failures:
        print(
            f"WARNING: Table 3 manuscript check differences "
            f"({len(failures)} strict + {len(recon_failures)} reconstruction):\n"
            + "\n".join(failures + recon_failures)
        )
    else:
        print(
            f"Table 3 — strict checks passed (tol={COEF_TOLERANCE}); "
            f"cols 4-5 reconstructions within {RECON_TOLERANCE} of published"
        )
    for name, exp, act in checks:
        print(f"  {name}: {act:.4f} (expected {exp:.4f})")
    for name, exp, act in recon_checks:
        print(f"  [recon] {name}: {act:.4f} (published {exp:.4f})")

    out_path = write_latex_table(models)
    print(f"  Wrote LaTeX table -> {out_path}")

    return models


if __name__ == "__main__":
    main()
